### PR TITLE
Workbench

### PR DESCRIPTION
**Pull request by multimeric**
Convert to the "new" workbench format. A rendered version can be found here: https://wehi-education.github.io/singularity-introduction/.

### CODE REVIEW

**Comment by multimeric** [comment]
Hi @jcohen02. Any thoughts on this? I can fix the conflict but I want to know if you are open to merging first.

**Comment by jcohen02** [comment]
> Hi @jcohen02. Any thoughts on this? I can fix the conflict but I want to know if you are open to merging first.

Hi @multimeric, sorry for the delay, been at a conference...definitely open, in principle, to merging this and thanks for opening this PR - the lesson needs to get switched across to the new workbench format. Have you been doing a fair bit of porting lessons to the new workbench? I know it requires significant changes. The PR looks a little complex and confusing - I'm unclear why it looks like it's trying to merge a long history of commits from as far back as 2020. Surely this should only be including a set of commits that sit on top of the current commit history changing the repo structure from the old template to the new infrastructure?

I need to look in more detail but I assume you've taken a fresh copy of the new workbench template, pulled in the commits containing the singularity lesson content and are then looking to merge this back into the original repo? If you've done this successfully with other repos and are happy with the way the PR is structured then in view of time, it may be best to go with this, resolve conflicts and then merge.

On the other hand, if I can find some time to look at this, I wonder if it might be an option start from a fresh fork and pull in content from the workbench template to switch this across to the new workbench structure?

**Comment by multimeric** [comment]
Yes I've done this before successfully. The commit history is actually correct, as far as I can tell. Only the last 4 commits are new, and they're the ones that introduce the changes. For some reason GitHub is showing all the preceding commits as well. In any case, I think you can probably squash and/or rebase this away when you merge it. If you look at the rendered copy, you'll see that the result is pretty sensible.

**Review by jcohen02 — COMMENTED** [review]
Thanks for this @multimeric, happy for you to go ahead and resolve merge conflicts if you're OK to make those changes, then I will merge this.

**Comment by multimeric** [comment]
Okay I pulled the changes then rebased my branch which seems to have fixed the horrendous commit list. The diff looks sensible too now. As before, you can view the rendered copy at https://wehi-education.github.io/singularity-introduction/.

**Comment by multimeric** [comment]
Any chance of a merge, @jcohen02?

**Review by jcohen02 — APPROVED** [review]
Many thanks for making this update @multimeric.

**Pull request merged**
